build:
  image: rustlang/rust:nightly
  script:
  - &print_version rustc --version && cargo --version
  - cargo build --release --verbose
  artifacts:
    paths:
    - target/release/pastebinrun

test:nightly: &test
  services:
  - postgres
  variables:
    POSTGRES_DB: db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  image: rustlang/rust:nightly
  script:
  - *print_version
  - DATABASE_URL=postgresql://user:password@postgres/db cargo test --verbose
