build:vite:
  stage: build
  image: node:16
  script:
    - npm ci
    - node_modules/.bin/vite build
  artifacts:
    paths:
      - dist

build:release: &build
  stage: test
  image: rust:latest
  script:
    - &init rustc --version && cargo --version
    - cargo build --release --verbose
  needs:
    - build:vite
  artifacts:
    paths:
      - languages.json
      - migrations
      - dist
      - target/release/pastebinrun

test:stable: &test
  stage: test
  services:
    - postgres
  variables:
    POSTGRES_DB: db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  image: rust:latest
  script:
    - *init
    - DATABASE_URL=postgresql://user:password@postgres/db cargo test --verbose --features=database_tests
  needs:
    - build:vite

test:clippy:
  <<: *test
  script:
    - *init
    - rustup component add clippy
    - cargo clippy --verbose

test:1.56:
  <<: *test
  image: rust:1.56

test:nightly:
  <<: *test
  image: rustlang/rust:nightly
  allow_failure: yes
