build:webpack:
  stage: build
  image: node:12.13
  script:
  - npm ci
  - node_modules/.bin/webpack
  artifacts:
    paths:
    - static
    - entry

build:release: &build
  stage: test
  image: rust:latest
  script:
  - &init rustc --version && cargo --version
  - cargo build --release --verbose
  artifacts:
    paths:
    - target/release/pastebinrun
    - migrations
    - static
  cache:
    key: release
    paths:
    - target

test:stable: &test
  stage: test
  services:
  - postgres
  variables:
    POSTGRES_DB: db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  image: rust:latest
  script:
  - *init
  - DATABASE_URL=postgresql://user:password@postgres/db cargo test --verbose --features=database_tests
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - target/

test:1.39:
  <<: *test
  image: rust:1.39

test:nightly:
  <<: *test
  image: rustlang/rust:nightly
