build:
  image: rust:latest
  script:
  - &init
    - apt update
    - apt install -y npm
    - rustc --version && cargo --version
    - npm ci
    - node_modules/.bin/webpack
  - cargo build --release --verbose
  artifacts:
    paths:
    - migrations
    - static
    - target/release/pastebinrun
  cache:
    key: release
    paths:
    - target/

test:stable: &test
  services:
  - postgres
  variables:
    POSTGRES_DB: db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  image: rust:latest
  script:
  - *init
  - DATABASE_URL=postgresql://user:password@postgres/db cargo test --verbose --features=database_tests
  cache:
    key: debug
    paths:
    - target/
