# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
when:
  - event: pull_request
  - event: push
    branch:
      - master
steps:
  npm-ci:
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npm ci
  eslint:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx eslint .
  prettier:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx prettier --check .
  reuse:
    group: test
    image: fsfe/reuse:2.1.0@sha256:888418362aa2a8ebea12d8dbfb41fa8eeabd0c423f42df7e3968af4cbb8d2ef1
    commands:
      - reuse lint
  rustfmt:
    group: test
    image: rust:1.74.1@sha256:6df01b907d5664cc3d4ad56c111b9d31bf8bf3ea6fb0ff7fa348e140ae54970d
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
  test:
    group: test
    image: rust:1.74.1@sha256:6df01b907d5664cc3d4ad56c111b9d31bf8bf3ea6fb0ff7fa348e140ae54970d
    commands:
      - cargo build --locked --verbose
      - cargo test --locked --verbose
  vitest:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx vitest run
