# SPDX-FileCopyrightText: 2023 Kamila Borowska <kamila@borowska.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
when:
  - event: pull_request
  - event: push
    branch:
      - master
steps:
  npm-ci:
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npm ci
  eslint:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx eslint .
  prettier:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx prettier --check .
  reuse:
    group: test
    image: fsfe/reuse:3.0.1@sha256:f8f4851e199f44a0e827ea7d248228e2045e26750707e4f5f1b5875caf4ac51a
    commands:
      - reuse lint
  rustfmt:
    group: test
    image: rust:1.76.0@sha256:a71cd88f9dd32fbdfa67c935f55165ddd89b7166e95de6c053c9bf33dd7381d5
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
  test:
    group: test
    image: rust:1.76.0@sha256:a71cd88f9dd32fbdfa67c935f55165ddd89b7166e95de6c053c9bf33dd7381d5
    commands:
      - cargo build --locked --verbose
      - cargo test --locked --verbose
  vitest:
    group: test
    image: node:18.18.2@sha256:e62671b4e91dcaf9f2cdb7b901aef948946b53ea642dbcba22779f1c602d2f2b
    commands:
      - npx vitest run
