[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "src/build.rs"

[dependencies]
ammonia = "3.1.1"
base64 = "0.13.0"
chrono = "0.4.19"
diesel = { version = "1.4.6", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
env_logger = { version = "0.8.3", default-features = false }
extension-trait = "1.0.0"
futures-util = "0.3.15"
itertools = "0.10.0"
log = "0.4.14"
mime = "0.3.16"
once_cell = "1.7.2"
pulldown-cmark = { version = "0.8.0", default-features = false, features = ["simd"] }
rand = "0.8.3"
reqwest = { version = "0.11.3", features = ["json"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
time-parse = "0.2.0"
tokio = { version = "1.6.1", features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3.1", default-features = false }

[build-dependencies]
ructe = "0.13.2"

[dev-dependencies]
scraper = { version = "0.12.0", default-features = false }

[features]
database_tests = []
sandbox_tests = []
