[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "src/build.rs"

[dependencies]
ammonia = "3.0.0"
base64 = "0.10.1"
chrono = "0.4.9"
diesel = { version = "1.4.1", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
env_logger = { version = "0.6.0", default-features = false }
extension-trait = "0.2.1"
futures03 = { version = "0.3.1", package = "futures" }
itertools = "0.8.1"
lazy_static = "1.3.0"
log = "0.4.6"
mime = "0.3.13"
pulldown-cmark = "0.5.0"
rand = "0.7.0"
reqwest = { version = "=0.10.0-alpha.2", features = ["json"] }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.41"
time-parse = "0.1.2"
tokio = "=0.2.0-alpha.6"
tokio-executor = { version = "0.2.0-alpha.4", features = ["blocking"] }
warp = { git = "https://github.com/seanmonstar/warp.git", rev = "fb64f24b6126efc618ca04a29acf1a7d4737c33c" }

[build-dependencies]
ructe = { version = "0.6.2" }

[dev-dependencies]
scraper = "0.10.1"

[features]
database_tests = []
sandbox_tests = []
