[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "src/build.rs"

[dependencies]
ammonia = "3.0.0"
base64 = "0.11.0"
chrono = "0.4.10"
diesel = { version = "1.4.3", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
env_logger = { version = "0.7.1", default-features = false }
futures = "0.1.29"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
itertools = "0.8.2"
log = "0.4.8"
mime = "0.3.16"
once_cell = "1.3.1"
pulldown-cmark = "0.6.1"
rand = "0.7.3"
reqwest = "0.9.24"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
time-parse = "0.1.2"
tokio-executor = { version = "=0.2.0-alpha.6", features = ["blocking"] }
warp = "0.1.20"

[build-dependencies]
ructe = { version = "0.9.0", features = ["mime03", "warp"] }

[dev-dependencies]
scraper = "0.11.0"

[features]
database_tests = []
sandbox_tests = []
