[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "src/build.rs"

[dependencies]
ammonia = "3.0.0"
base64 = "0.10.1"
chrono = "0.4.9"
diesel = { version = "1.4.1", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
env_logger = { version = "0.6.0", default-features = false }
futures = "0.1.28"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
itertools = "0.8.1"
log = "0.4.6"
mime = "0.3.13"
once_cell = "1.2.0"
pulldown-cmark = "0.5.0"
rand = "0.7.0"
reqwest = "0.9.19"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.41"
time-parse = "0.1.2"
tokio = { version = "0.2.0", features = ["blocking"] }
warp = "0.1.15"

[build-dependencies]
ructe = { version = "0.6.2", features = ["mime03", "warp"] }
walkdir = "2.2.9"

[dev-dependencies]
scraper = "0.10.1"

[features]
database_tests = []
sandbox_tests = []
