# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2021"
license = "AGPL-3.0-or-later"
build = "buildSrc/build.rs"

[dependencies]
ammonia = "3.3.0"
chrono = { version = "0.4.31", default-features = false }
diesel = { version = "2.1.3", features = ["chrono"] }
diesel_migrations = "2.1.0"
iso8601-duration = { version = "0.2.0", features = ["chrono"] }
itertools = "0.11.0"
log = "0.4.20"
once_cell = "1.18.0"
prometheus = { version = "0.13.3", features = ["process"], default-features = false }
pulldown-cmark = { version = "0.9.3", default-features = false }
rand = "0.8.5"
reqwest = { version = "0.11.22", features = ["json"] }
rocket = { version = "=0.5.0-rc.4", features = ["json"] }
rocket_dyn_templates = { version = "=0.1.0-rc.4", features = ["tera"] }
rocket_sync_db_pools = { version = "=0.1.0-rc.4", features = ["diesel_postgres_pool"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde_with = "3.4.0"

[build-dependencies]
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"

[features]
database_tests = []
sandbox_tests = []
