[package]
name = "pastebinrun"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "src/build.rs"

[dependencies]
ammonia = "3.0.0"
base64 = "0.11.0"
chrono = "0.4.10"
diesel = { version = "1.4.3", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
env_logger = { version = "0.7.1", default-features = false }
extension-trait = "0.2.1"
futures = "0.3.1"
itertools = "0.8.2"
log = "0.4.8"
mime = "0.3.14"
once_cell = "1.2.0"
pulldown-cmark = "0.6.1"
rand = "0.7.2"
reqwest = { git = "https://github.com/seanmonstar/reqwest.git", rev = "24abf2fcbdabbc63136677bc440788271484d103", features = ["json"] }
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
time-parse = "0.1.2"
tokio = { version = "0.2.4", features = ["blocking"] }
warp = { git = "https://github.com/seanmonstar/warp.git", rev = "b6cbcca0914cfb435ae19c1aab86c0ffa0316322" }

[build-dependencies]
ructe = "0.8.0"

[dev-dependencies]
scraper = "0.11.0"

[features]
database_tests = []
sandbox_tests = []
