# SPDX-FileCopyrightText: 2023 Konrad Borowski <konrad@borowski.pw>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

when:
  - event: pull_request
  - event: push
    branch:
      - master

steps:
  rustfmt:
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
